// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reciicer.Data;

#nullable disable

namespace Reciicer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250412011607_AuditInformations")]
    partial class AuditInformations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "298f1256-ec97-4797-966c-d813afa14f70",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "8a62bbbf-8420-459c-94d3-9da153f3803f",
                            Name = "Operador",
                            NormalizedName = "OPERADOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Admin",
                            UserId = "8868b1f4-812f-4bbd-a438-1b25f7241f78"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "PontoColetaId",
                            ClaimValue = "1",
                            UserId = "8868b1f4-812f-4bbd-a438-1b25f7241f78"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Operador",
                            UserId = "02f34b97-229a-4764-ba00-2298903959c5"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "PontoColetaId",
                            ClaimValue = "2",
                            UserId = "02f34b97-229a-4764-ba00-2298903959c5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8868b1f4-812f-4bbd-a438-1b25f7241f78",
                            RoleId = "298f1256-ec97-4797-966c-d813afa14f70"
                        },
                        new
                        {
                            UserId = "02f34b97-229a-4764-ba00-2298903959c5",
                            RoleId = "8a62bbbf-8420-459c-94d3-9da153f3803f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reciicer.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabela")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontuacaoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "777.777.777-77",
                            DataCadastro = new DateTime(2023, 10, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "jurandir@gmail.com",
                            Nome = "Jurandir",
                            PontuacaoTotal = 0,
                            Telefone = "(65) 4984-9849"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "544.894.849-98",
                            DataCadastro = new DateTime(2023, 10, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "judit@gmail.com",
                            Nome = "Judit",
                            PontuacaoTotal = 0,
                            Telefone = "(54) 4545-4544"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "894.399.251-32",
                            DataCadastro = new DateTime(2023, 10, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "astolfo@gmail.com",
                            Nome = "Astolfo",
                            PontuacaoTotal = 0,
                            Telefone = "(92) 98308-7102"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "544.484.948-49",
                            DataCadastro = new DateTime(2024, 11, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "manoel@padaria.com",
                            Nome = "Teobaldo",
                            PontuacaoTotal = 0,
                            Telefone = "(82) 8959-8598"
                        },
                        new
                        {
                            Id = 6,
                            CPF = "494.292.982-82",
                            DataCadastro = new DateTime(2024, 10, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "nelson@gmail.com",
                            Nome = "Nelson",
                            PontuacaoTotal = 0,
                            Telefone = "(51) 6165-5551"
                        },
                        new
                        {
                            Id = 7,
                            CPF = "594.985.982-29",
                            DataCadastro = new DateTime(2024, 10, 3, 20, 28, 26, 290, DateTimeKind.Unspecified),
                            Email = "beth@gmail.com",
                            Nome = "Beth",
                            PontuacaoTotal = 0,
                            Telefone = "(54) 4988-5165"
                        },
                        new
                        {
                            Id = 8,
                            CPF = "889.248.484-98",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zezin@gmail.com",
                            Nome = "Zezin",
                            PontuacaoTotal = 0,
                            Telefone = "(59) 8988-8995"
                        },
                        new
                        {
                            Id = 9,
                            CPF = "944.984.298-24",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikita@gmail.com",
                            Nome = "Nikita",
                            PontuacaoTotal = 0,
                            Telefone = "(89) 4494-9849"
                        },
                        new
                        {
                            Id = 1010,
                            CPF = "984.984.984-84",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linkedin@gmail.com",
                            Nome = "Linkedin",
                            PontuacaoTotal = 0,
                            Telefone = "(49) 8498-4984"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.ClientePremiacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PremiacaoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PremiacaoId");

                    b.ToTable("ClientePremiacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 3,
                            DataOperacao = new DateTime(2024, 11, 21, 4, 23, 6, 153, DateTimeKind.Local),
                            PremiacaoId = 3
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2024, 12, 3, 20, 21, 1, 913, DateTimeKind.Local),
                            PremiacaoId = 3
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 7,
                            DataOperacao = new DateTime(2025, 1, 21, 2, 15, 38, 995, DateTimeKind.Local),
                            PremiacaoId = 3
                        },
                        new
                        {
                            Id = 1004,
                            ClienteId = 1010,
                            DataOperacao = new DateTime(2025, 2, 4, 17, 27, 18, 12, DateTimeKind.Local),
                            PremiacaoId = 3
                        },
                        new
                        {
                            Id = 1005,
                            ClienteId = 8,
                            DataOperacao = new DateTime(2025, 2, 19, 23, 37, 4, 812, DateTimeKind.Local),
                            PremiacaoId = 3
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Coleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoGanha")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("Coleta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2025, 3, 24, 16, 50, 54, 765, DateTimeKind.Unspecified),
                            PontoColetaId = 2,
                            PontuacaoGanha = 10
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2024, 9, 4, 20, 8, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 54
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 3,
                            DataOperacao = new DateTime(2024, 10, 17, 20, 9, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 20
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2024, 11, 17, 20, 10, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 6
                        },
                        new
                        {
                            Id = 6,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2024, 11, 22, 20, 11, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 150
                        },
                        new
                        {
                            Id = 7,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2024, 12, 3, 20, 20, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 115
                        },
                        new
                        {
                            Id = 8,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2024, 12, 2, 20, 20, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 200
                        },
                        new
                        {
                            Id = 9,
                            ClienteId = 6,
                            DataOperacao = new DateTime(2024, 11, 14, 20, 43, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 2,
                            PontuacaoGanha = 30
                        },
                        new
                        {
                            Id = 10,
                            ClienteId = 7,
                            DataOperacao = new DateTime(2024, 10, 8, 20, 44, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 2,
                            PontuacaoGanha = 260
                        },
                        new
                        {
                            Id = 11,
                            ClienteId = 5,
                            DataOperacao = new DateTime(2024, 12, 18, 0, 18, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 1000
                        },
                        new
                        {
                            Id = 12,
                            ClienteId = 3,
                            DataOperacao = new DateTime(2024, 12, 11, 0, 21, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 250
                        },
                        new
                        {
                            Id = 13,
                            ClienteId = 7,
                            DataOperacao = new DateTime(2025, 1, 9, 2, 16, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 75
                        },
                        new
                        {
                            Id = 14,
                            ClienteId = 9,
                            DataOperacao = new DateTime(2025, 1, 22, 14, 54, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 0
                        },
                        new
                        {
                            Id = 1014,
                            ClienteId = 1010,
                            DataOperacao = new DateTime(2025, 2, 4, 17, 25, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 2,
                            PontuacaoGanha = 120
                        },
                        new
                        {
                            Id = 1015,
                            ClienteId = 1010,
                            DataOperacao = new DateTime(2025, 2, 4, 17, 26, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 2,
                            PontuacaoGanha = 200
                        },
                        new
                        {
                            Id = 1016,
                            ClienteId = 1010,
                            DataOperacao = new DateTime(2025, 2, 3, 17, 51, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 6
                        },
                        new
                        {
                            Id = 1017,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2023, 3, 12, 18, 41, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 75
                        },
                        new
                        {
                            Id = 1018,
                            ClienteId = 7,
                            DataOperacao = new DateTime(2023, 7, 7, 22, 2, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 100
                        },
                        new
                        {
                            Id = 1019,
                            ClienteId = 8,
                            DataOperacao = new DateTime(2025, 2, 19, 23, 36, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 200
                        },
                        new
                        {
                            Id = 2085,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2025, 3, 4, 1, 57, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 120
                        },
                        new
                        {
                            Id = 2090,
                            ClienteId = 7,
                            DataOperacao = new DateTime(2025, 3, 13, 3, 40, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 0
                        },
                        new
                        {
                            Id = 2091,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2025, 3, 13, 3, 41, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 0
                        },
                        new
                        {
                            Id = 2092,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2025, 3, 5, 3, 42, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 0
                        },
                        new
                        {
                            Id = 3090,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2025, 3, 20, 19, 2, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 4
                        },
                        new
                        {
                            Id = 3091,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2025, 2, 26, 19, 40, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 90
                        },
                        new
                        {
                            Id = 3092,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2025, 3, 18, 19, 41, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 120
                        },
                        new
                        {
                            Id = 4103,
                            ClienteId = 2,
                            DataOperacao = new DateTime(2025, 3, 4, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 20
                        },
                        new
                        {
                            Id = 4105,
                            ClienteId = 1,
                            DataOperacao = new DateTime(2025, 3, 6, 19, 51, 0, 0, DateTimeKind.Unspecified),
                            PontoColetaId = 1,
                            PontuacaoGanha = 0
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Cooperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Cooperativa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "00.000.000",
                            Email = "coop@gmail.com",
                            Nome = "Cooperativa de Reciclagem"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "48489484848",
                            Email = "comlurb@gmail.com",
                            Nome = "Comlurb"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Rua", "Numero", "Bairro", "Cep")
                        .IsUnique();

                    b.ToTable("Endereco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Bairro 1",
                            Cep = "60000-000",
                            Cidade = "Cidade 1",
                            Estado = "Estado 1",
                            Numero = 1,
                            Rua = "Rua 1"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Bairro 2",
                            Cep = "60000-001",
                            Cidade = "Cidade 2",
                            Estado = "Estado 2",
                            Numero = 2,
                            Rua = "Rua 2"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoArmazenado")
                        .HasColumnType("int");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeArmazenada")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("Estoque", t =>
                        {
                            t.HasCheckConstraint("CHK_Estoque_Capacidade", "PesoArmazenado + QuantidadeArmazenada <= Capacidade");

                            t.HasCheckConstraint("CHK_Estoque_Capacidade_NaoNegativa", "Capacidade >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 20,
                            Codigo = "PR001",
                            PesoArmazenado = 4,
                            PontoColetaId = 1,
                            QuantidadeArmazenada = 16,
                            Tipo = "Interno"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 5,
                            Codigo = "PRN001",
                            PesoArmazenado = 0,
                            PontoColetaId = 2,
                            QuantidadeArmazenada = 0,
                            Tipo = "Externo"
                        },
                        new
                        {
                            Id = 1007,
                            Capacidade = 10,
                            Codigo = "PN002",
                            PesoArmazenado = 3,
                            PontoColetaId = 1,
                            QuantidadeArmazenada = 6,
                            Tipo = "Normal"
                        },
                        new
                        {
                            Id = 1008,
                            Capacidade = 10,
                            Codigo = "PN003",
                            PesoArmazenado = 2,
                            PontoColetaId = 1,
                            QuantidadeArmazenada = 0,
                            Tipo = "Normal"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.EstoqueMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("MaterialId");

                    b.ToTable("EstoqueMaterial");

                    b.HasData(
                        new
                        {
                            Id = 158,
                            EstoqueId = 1,
                            MaterialId = 4,
                            Peso = 8,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 159,
                            EstoqueId = 1007,
                            MaterialId = 4,
                            Peso = 2,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 163,
                            EstoqueId = 1,
                            MaterialId = 5,
                            Peso = 6,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 164,
                            EstoqueId = 1007,
                            MaterialId = 5,
                            Peso = 2,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 171,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 172,
                            EstoqueId = 1008,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1165,
                            EstoqueId = 1,
                            MaterialId = 5,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1166,
                            EstoqueId = 1,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 4
                        },
                        new
                        {
                            Id = 1167,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 1168,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 1169,
                            EstoqueId = 1008,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 2163,
                            EstoqueId = 2,
                            MaterialId = 5,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2164,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2165,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2166,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2167,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2168,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2169,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2170,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2171,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2172,
                            EstoqueId = 1008,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2173,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2174,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2175,
                            EstoqueId = 1007,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2176,
                            EstoqueId = 1007,
                            MaterialId = 4,
                            Peso = 2,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2177,
                            EstoqueId = 1,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2178,
                            EstoqueId = 1,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2179,
                            EstoqueId = 1,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2180,
                            EstoqueId = 1,
                            MaterialId = 4,
                            Peso = 2,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2181,
                            EstoqueId = 1007,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2182,
                            EstoqueId = 1008,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 0
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontuacaoPeso")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoUnidade")
                        .HasColumnType("int");

                    b.Property<int?>("TempoDegradacao")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TipoMaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("TipoMaterialId");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Papelão",
                            Nome = "Papelão",
                            PontuacaoPeso = 20,
                            PontuacaoUnidade = 2,
                            TempoDegradacao = 162000,
                            TipoMaterialId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Papel de presente",
                            Nome = "Papel Presente",
                            PontuacaoPeso = 10,
                            PontuacaoUnidade = 5,
                            TempoDegradacao = 150,
                            TipoMaterialId = 2
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Garrafa PET - Polietileno Tereftalato",
                            Nome = "PET",
                            PontuacaoPeso = 15,
                            PontuacaoUnidade = 3,
                            TempoDegradacao = 18000,
                            TipoMaterialId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Copo de Vidro",
                            Nome = "Copo",
                            PontuacaoPeso = 25,
                            PontuacaoUnidade = 10,
                            TempoDegradacao = 1000000,
                            TipoMaterialId = 3
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Latinha",
                            Nome = "Alumínio",
                            PontuacaoPeso = 10,
                            PontuacaoUnidade = 2,
                            TempoDegradacao = 1000,
                            TipoMaterialId = 4
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Material_Coleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColetaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Material_Coleta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColetaId = 1,
                            MaterialId = 3,
                            Peso = 5,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2,
                            ColetaId = 3,
                            MaterialId = 1,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 3,
                            ColetaId = 3,
                            MaterialId = 4,
                            Peso = 2,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 4,
                            ColetaId = 4,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 5,
                            ColetaId = 5,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 6,
                            ColetaId = 6,
                            MaterialId = 3,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 7,
                            ColetaId = 7,
                            MaterialId = 5,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 8,
                            ColetaId = 7,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 9,
                            ColetaId = 8,
                            MaterialId = 1,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 10,
                            ColetaId = 9,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 3
                        },
                        new
                        {
                            Id = 11,
                            ColetaId = 10,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 12,
                            ColetaId = 10,
                            MaterialId = 1,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 13,
                            ColetaId = 11,
                            MaterialId = 1,
                            Peso = 50,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 14,
                            ColetaId = 12,
                            MaterialId = 4,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 15,
                            ColetaId = 13,
                            MaterialId = 3,
                            Peso = 5,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 16,
                            ColetaId = 14,
                            MaterialId = 1,
                            Peso = 20,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1016,
                            ColetaId = 1014,
                            MaterialId = 2,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1017,
                            ColetaId = 1014,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 1018,
                            ColetaId = 1015,
                            MaterialId = 1,
                            Peso = 10,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1019,
                            ColetaId = 1016,
                            MaterialId = 3,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 1020,
                            ColetaId = 1017,
                            MaterialId = 3,
                            Peso = 5,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 1021,
                            ColetaId = 1018,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 1022,
                            ColetaId = 1019,
                            MaterialId = 2,
                            Peso = 20,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2114,
                            ColetaId = 2085,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 12
                        },
                        new
                        {
                            Id = 3119,
                            ColetaId = 3090,
                            MaterialId = 5,
                            Peso = 0,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 3120,
                            ColetaId = 3091,
                            MaterialId = 3,
                            Peso = 6,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 3121,
                            ColetaId = 3092,
                            MaterialId = 1,
                            Peso = 6,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 4133,
                            ColetaId = 4103,
                            MaterialId = 4,
                            Peso = 0,
                            Quantidade = 2
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.PontoColeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PontoColeta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnderecoId = 1,
                            Nome = "Parmê"
                        },
                        new
                        {
                            Id = 2,
                            EnderecoId = 2,
                            Nome = "Supermercado Guanabara"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Premiacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontuacaoRequerida")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Premiacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Ingresso para 1 sessão de cinema",
                            Nome = "Ingresso UCI",
                            PontuacaoRequerida = 1000
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            Descricao = "Desconto de 10% em compras até R$200,00 ",
                            Nome = "Desconto 10%",
                            PontuacaoRequerida = 100
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Boné personalizado ",
                            Nome = "Boné",
                            PontuacaoRequerida = 200
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Recolhimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CooperativaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRecolhimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CooperativaId");

                    b.ToTable("Recolhimento");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            CooperativaId = 2,
                            DataRecolhimento = new DateTime(2025, 3, 25, 19, 4, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            CooperativaId = 1,
                            DataRecolhimento = new DateTime(2025, 3, 18, 19, 4, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            CooperativaId = 2,
                            DataRecolhimento = new DateTime(2025, 3, 5, 19, 42, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            CooperativaId = 2,
                            DataRecolhimento = new DateTime(2025, 3, 5, 1, 54, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            CooperativaId = 1,
                            DataRecolhimento = new DateTime(2025, 3, 7, 2, 18, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.RecolhimentoEstoqueMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstoqueMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("RecolhimentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueMaterialId");

                    b.HasIndex("RecolhimentoId");

                    b.ToTable("RecolhimentoEstoqueMaterial");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            EstoqueMaterialId = 1165,
                            Peso = 0,
                            Quantidade = 1,
                            RecolhimentoId = 8
                        },
                        new
                        {
                            Id = 6,
                            EstoqueMaterialId = 1165,
                            Peso = 0,
                            Quantidade = 1,
                            RecolhimentoId = 9
                        },
                        new
                        {
                            Id = 9,
                            EstoqueMaterialId = 1169,
                            Peso = 1,
                            Quantidade = 0,
                            RecolhimentoId = 13
                        },
                        new
                        {
                            Id = 1002,
                            EstoqueMaterialId = 1169,
                            Peso = 2,
                            Quantidade = 0,
                            RecolhimentoId = 14
                        },
                        new
                        {
                            Id = 1003,
                            EstoqueMaterialId = 2163,
                            Peso = 0,
                            Quantidade = 2,
                            RecolhimentoId = 15
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.TipoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TipoMaterial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Plástico",
                            Nome = "Plástico"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Papel",
                            Nome = "Papel"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Vidro",
                            Nome = "Vidro"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Metal",
                            Nome = "Metal"
                        });
                });

            modelBuilder.Entity("Reciicer.Models.Entities.UsuarioIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8868b1f4-812f-4bbd-a438-1b25f7241f78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1baef787-8bf1-4f46-a40d-7cce9cc00a4e",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELOGUtUv5slutFj/g2ySNtpAyK6JnEzlfSGIQVH2hL8onfOArNzzqS3hzh4KBbfBlg==",
                            PhoneNumberConfirmed = false,
                            PontoColetaId = 1,
                            SecurityStamp = "5aa8cd4a-9c6d-476c-a246-56de4783a6e5",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "02f34b97-229a-4764-ba00-2298903959c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b3e54c7-8c70-4d20-9820-96fad61cd9d0",
                            Email = "operador@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "OPERADOR@GMAIL.COM",
                            NormalizedUserName = "OPERADOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEHQ7mga+DIAlOUen1rubIYWrGtJL/2ELlGuZQrZgvy/1u0aPPJa1UHG0VWqHJa06uA==",
                            PhoneNumberConfirmed = false,
                            PontoColetaId = 2,
                            SecurityStamp = "be260f41-b82c-47fe-9051-e78ed3500d00",
                            TwoFactorEnabled = false,
                            UserName = "operador"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reciicer.Models.Entities.ClientePremiacao", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Cliente", "Cliente")
                        .WithMany("ClientePremiacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.Premiacao", "Premiacao")
                        .WithMany("ClientePremiacaos")
                        .HasForeignKey("PremiacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Premiacao");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Coleta", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Cliente", "Cliente")
                        .WithMany("Coletas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.PontoColeta", "PontoColeta")
                        .WithMany("Coletas")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Estoque", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.PontoColeta", "PontoColeta")
                        .WithMany()
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.EstoqueMaterial", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Estoque", "Estoque")
                        .WithMany("EstoqueMateriais")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.Material", "Material")
                        .WithMany("EstoqueMateriais")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Material", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.TipoMaterial", "TipoMaterial")
                        .WithMany("Materiais")
                        .HasForeignKey("TipoMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMaterial");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Material_Coleta", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Coleta", "Coleta")
                        .WithMany("Material_Coletas")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.Material", "Material")
                        .WithMany("Material_Coletas")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleta");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.PontoColeta", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Recolhimento", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.Cooperativa", "Cooperativa")
                        .WithMany("Recolhimentos")
                        .HasForeignKey("CooperativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperativa");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.RecolhimentoEstoqueMaterial", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.EstoqueMaterial", "EstoqueMaterial")
                        .WithMany("RecolhimentoEstoqueMateriais")
                        .HasForeignKey("EstoqueMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reciicer.Models.Entities.Recolhimento", "Recolhimento")
                        .WithMany("RecolhimentoEstoqueMateriais")
                        .HasForeignKey("RecolhimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstoqueMaterial");

                    b.Navigation("Recolhimento");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.UsuarioIdentity", b =>
                {
                    b.HasOne("Reciicer.Models.Entities.PontoColeta", "PontoColeta")
                        .WithMany("UsuarioIdentities")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Cliente", b =>
                {
                    b.Navigation("ClientePremiacoes");

                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Coleta", b =>
                {
                    b.Navigation("Material_Coletas");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Cooperativa", b =>
                {
                    b.Navigation("Recolhimentos");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Estoque", b =>
                {
                    b.Navigation("EstoqueMateriais");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.EstoqueMaterial", b =>
                {
                    b.Navigation("RecolhimentoEstoqueMateriais");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Material", b =>
                {
                    b.Navigation("EstoqueMateriais");

                    b.Navigation("Material_Coletas");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.PontoColeta", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("UsuarioIdentities");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Premiacao", b =>
                {
                    b.Navigation("ClientePremiacaos");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.Recolhimento", b =>
                {
                    b.Navigation("RecolhimentoEstoqueMateriais");
                });

            modelBuilder.Entity("Reciicer.Models.Entities.TipoMaterial", b =>
                {
                    b.Navigation("Materiais");
                });
#pragma warning restore 612, 618
        }
    }
}
